spec:
  inputs:
    cloud-provider:
      default: 'aws'
      type: string
      description: Which cloud provider to use for VPN
      options:
        - 'aws'
        - 'gcp'
        - 'do'
    REGION:
      description: AWS region to deploy the instance in
      rules:
        - if: $[[ inputs.cloud-provider ]] == 'aws'
          default: 'ap-southeast-1'
          options:
            - 'us-east-1'
            - 'us-east-2'
            - 'us-west-1'
            - 'us-west-2'
            - 'af-south-1'
            - 'ap-east-1'
            - 'ap-east-2'
            - 'ap-south-1'
            - 'ap-south-2'
            - 'ap-northeast-1'
            - 'ap-northeast-2'
            - 'ap-northeast-3'
            - 'ap-southeast-1'
            - 'ap-southeast-2'
            - 'ap-southeast-3'
            - 'ap-southeast-4'
            - 'ap-southeast-5'
            - 'ap-southeast-6'
            - 'ap-southeast-7'
            - 'ca-central-1'
            - 'ca-west-1'
            - 'eu-central-1'
            - 'eu-central-2'
            - 'eu-west-1'
            - 'eu-west-2'
            - 'eu-west-3'
            - 'eu-south-1'
            - 'eu-south-2'
            - 'eu-north-1'
            - 'il-central-1'
            - 'me-south-1'
            - 'me-south-2'
            - 'me-central-1'
            - 'mx-central-1'
            - 'sa-east-1'
            - 'us-gov-east-1'
            - 'us-gov-west-1'
            - 'cn-north-1'
            - 'cn-northwest-1'
        - if: $[[ inputs.cloud-provider ]] == 'gcp'
          default: 'asia-southeast1'
          options:
            - 'africa-south1'
            - 'asia-east1'
            - 'asia-east2'
            - 'asia-northeast1'
            - 'asia-northeast2'
            - 'asia-northeast3'
            - 'asia-south1'
            - 'asia-south2'
            - 'asia-southeast1'
            - 'asia-southeast2'
            - 'australia-southeast1'
            - 'australia-southeast2'
            - 'europe-central2'
            - 'europe-north1'
            - 'europe-north2'
            - 'europe-southwest1'
            - 'europe-west1'
            - 'europe-west2'
            - 'europe-west3'
            - 'europe-west4'
            - 'europe-west6'
            - 'europe-west8'
            - 'europe-west9'
            - 'europe-west10'
            - 'europe-west12'
            - 'me-central1'
            - 'me-central2'
            - 'me-west1'
            - 'northamerica-northeast1'
            - 'northamerica-northeast2'
            - 'northamerica-south1'
            - 'southamerica-east1'
            - 'southamerica-west1'
            - 'us-central1'
            - 'us-east1'
            - 'us-east4'
            - 'us-east5'
            - 'us-south1'
            - 'us-west1'
            - 'us-west2'
            - 'us-west3'
            - 'us-west4'
        - if: $[[ inputs.cloud-provider ]] == 'do'
          default: 'sgp1'
          options:
            - 'nyc1'
            - 'nyc2'
            - 'nyc3'
            - 'ams3'
            - 'sfo2'
            - 'sfo3'
            - 'sgp1'
            - 'lon1'
            - 'fra1'
            - 'tor1'
            - 'blr1'
            - 'syd1'
            - 'atl1'
---
stages:
  - provision
  - install
  - generate
  - destroy

.provision-instance-template:
  needs: []
  stage: provision
  image: 
    name: fureasu346/opentofu:v1.11.5
    entrypoint: [""]
  script:
    - sed -i "s|dev|$CI_PIPELINE_ID|" backend.tf
    - cat ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]/ci.auto.tfvars
    - tofu init
    - tofu plan -out $[[ inputs.cloud-provider ]].tfplan
    - tofu apply $[[ inputs.cloud-provider ]].tfplan
    - tofu show -json > $[[ inputs.cloud-provider ]]-${CI_PIPELINE_ID}.json
  artifacts:
    paths:
      - $[[ inputs.cloud-provider ]]-${CI_PIPELINE_ID}.json
    expire_in: 30 days
  cache:
    key: tofu-files
    paths:
      - ${CI_PROJECT_DIR}/.terraform

.aws-init: &aws-init
  rules:
    - if: '"$[[ inputs.cloud-provider ]]" == "aws" && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
      when: manual
  before_script:
    - cd ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]
    - |
      declare -a VARS=('AWS_INSTANCE_TYPE' 'AWS_KEYPAIR_NAME' 'REGION' 'AWS_ACCESS_KEY' 'AWS_SECRET_KEY' 'AWS_VPC_CIDR')
      for VAR in "${VARS[@]}"; do
        if [[ -v $VAR ]]; then 
          echo "$VAR is set"
          tfvar="${VAR#AWS_}"
          printf '%s="%s"\n' "$tfvar" "${!VAR}" >> ci.auto.tfvars
        fi
      done
    - ls ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]/ci.auto.tfvars

aws-provision:
  <<: *aws-init
  extends: .provision-instance-template

tear-down:
  <<: *aws-init
  stage: destroy
  image: 
    name: fureasu346/opentofu:v1.11.5
    entrypoint: [""]
  script:
    - cd ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]
    - tofu init
    - tofu plan -destroy -out $[[ inputs.cloud-provider ]].destroy.tfplan
    - tofu apply $[[ inputs.cloud-provider ]].destroy.tfplan
  cache:
    key: tofu-files
    paths:
      - ${CI_PROJECT_DIR}/.terraform

.remote-access-template:
    dependencies: $[[ inputs.cloud-provider ]]-provision
    before_script:
      - chmod 400 "$SSH_PRIV_KEY"
      - mkdir -p ~/.ssh
      - ssh-keyscan -H "$INSTANCE_IP" >> ~/.ssh/known_hosts
