spec:
  inputs:
    cloud-provider:
      type: string
      default: 'aws'
      description: "Cloud provider for VPN"
      options: ['aws', 'gcp', 'do']
    region:
      description: "Regional deployment target"
      rules:
        - if: $[[ inputs.cloud-provider ]] == 'aws'
          default: 'ap-southeast-1'
          options: [
            'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2', 'af-south-1', 'ap-east-1', 'ap-east-2', 
            'ap-south-1', 'ap-south-2', 'ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3', 'ap-southeast-1', 
            'ap-southeast-2', 'ap-southeast-3', 'ap-southeast-4', 'ap-southeast-5', 'ap-southeast-6', 
            'ap-southeast-7', 'ca-central-1', 'ca-west-1', 'eu-central-1', 'eu-central-2', 'eu-west-1', 
            'eu-west-2', 'eu-west-3', 'eu-south-1', 'eu-south-2', 'eu-north-1', 'il-central-1', 'me-south-1', 
            'me-south-2', 'me-central-1', 'mx-central-1', 'sa-east-1', 'us-gov-east-1', 'us-gov-west-1', 
            'cn-north-1', 'cn-northwest-1'
          ]
        - if: $[[ inputs.cloud-provider ]] == 'gcp'
          default: 'asia-southeast1'
          options: [
            'africa-south1', 'asia-east1', 'asia-east2', 'asia-northeast1', 'asia-northeast2', 'asia-northeast3', 
            'asia-south1', 'asia-south2', 'asia-southeast1', 'asia-southeast2', 'australia-southeast1', 
            'australia-southeast2', 'europe-central2', 'europe-north1', 'europe-north2', 'europe-southwest1', 
            'europe-west1', 'europe-west2', 'europe-west3', 'europe-west4', 'europe-west6', 'europe-west8', 
            'europe-west9', 'europe-west10', 'europe-west12', 'me-central1', 'me-central2', 'me-west1', 
            'northamerica-northeast1', 'northamerica-northeast2', 'northamerica-south1', 'southamerica-east1', 
            'southamerica-west1', 'us-central1', 'us-east1', 'us-east4', 'us-east5', 'us-south1', 'us-west1', 
            'us-west2', 'us-west3', 'us-west4'
          ]
        - if: $[[ inputs.cloud-provider ]] == 'do'
          default: 'sgp1'
          options: ['nyc1', 'nyc2', 'nyc3', 'ams3', 'sfo2', 'sfo3', 'sgp1', 'lon1', 'fra1', 'tor1', 'blr1', 'syd1', 'atl1']
    instance-type:
      description: "VPN server instance type"
      rules:
        - if: $[[ inputs.cloud-provider ]] == 'aws'
          default: 't2.micro'
          options: ['t2.micro', 't3.micro', 't2.small', 't3.small', 't2.medium', 't3.medium']
        - if: $[[ inputs.cloud-provider ]] == 'gcp'
          default: 'e2.micro'
          options: ['e2.micro', 'e2.small', 'e2.medium']
        - if: $[[ inputs.cloud-provider ]] == 'do'
          default: 's-1vcpu-1gb'
          options: ['s-1vcpu-1gb', 's-1vcpu-512mb-10gb', 's-1vcpu-2gb']
    initial-key-names:
      description: "Key names to generate initially in VPN servers. Please enter a comma separated string"
      type: string
      default: 'key1,key2'
---
stages:
  - provision
  - install
  - generate
  - destroy

.provision-instance-template:
  needs: []
  stage: provision
  image: 
    name: fureasu346/opentofu:v1.11.5
    entrypoint: [""]
  environment:
    name: $[[ inputs.cloud-provider ]]-$[[ inputs.region ]]
    on_stop: $[[ inputs.cloud-provider ]]-tear-down
  script:
    - tofu init -input=false -reconfigure
    - tofu plan -input=false -out ${CI_PIPELINE_ID}.tfplan
    - tofu apply -input=false ${CI_PIPELINE_ID}.tfplan
    - tofu show -json > ${CI_PIPELINE_ID}.json
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]/${CI_PIPELINE_ID}.json
    expire_in: 30 days
  cache:
    key: tofu-files
    paths:
      - ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]/.terraform

.all-init: &all-init
  - cd ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]
  - sed -i "s|dev|$CI_PIPELINE_ID|" backend.tf
  - echo "Setting global variables"
  - printf '%s="%s"\n' "gl_user" "$CI_USER" >> ci.auto.tfvars
  - printf '%s="%s"\n' "gl_pat" "$CI_PAT" >> ci.auto.tfvars
  - |
    for VAR in "${VARS[@]}"; do
      if [ -n "${!VAR+x}" ]; then
        echo "$VAR is set"
        tfvar="${VAR#AWS_}"
        tfvar_lc="${tfvar,,}"
        printf '%s="%s"\n' "$tfvar_lc" "${!VAR}" >> ci.auto.tfvars
      else
        echo "$VAR is not set. Using default"
      fi
    done

.aws-init: &aws-init
  variables:
    AWS_REGION: $[[ inputs.region ]]
    AWS_INSTANCE_TYPE: $[[ inputs.instance-type ]]
  rules:
    - if: '"$[[ inputs.cloud-provider ]]" == "aws" && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
      when: manual
  before_script:
    - declare -a VARS=( 'AWS_REGION' 'AWS_INSTANCE_TYPE' 'AWS_KEYPAIR_NAME' 'AWS_ACCESS_KEY' 'AWS_SECRET_KEY' 'AWS_VPC_CIDR' )
    - *all-init

aws-provision:
  <<: *aws-init
  extends: .provision-instance-template

.tear-down-defaults: &tear-down-defaults
  needs:
    - job: $[[ inputs.cloud-provider ]]-provision
      artifacts: false
      optional: false
  environment:
    name: $[[ inputs.cloud-provider ]]-$[[ inputs.region ]]
    action: stop
  stage: destroy
  image: 
    name: fureasu346/opentofu:v1.11.5
    entrypoint: [""]
  script:
    - tofu init -input=false -reconfigure
    - tofu plan -input=false -destroy -out ${CI_PIPELINE_ID}.destroy.tfplan
    - tofu apply -input=false ${CI_PIPELINE_ID}.destroy.tfplan
    - echo "Deleting state file"
    - |
      curl --request DELETE \
        --header "Private-Token: $CI_PAT" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PIPELINE_ID}"
    - echo "Deployment torn down and tfstate file deleted"
  cache:
    key: tofu-files
    paths:
      - ${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]/.terraform
  manual_confirmation: "Are you sure you want to stop the $[[ inputs.cloud-provider ]]-$[[ inputs.region ]] environment"

aws-tear-down:
  <<: [*aws-init, *tear-down-defaults]

.remote-access-template:
  image: fureasu346/pipeline-util:v1
  needs:
    - job: $[[ inputs.cloud-provider ]]-provision
      artifacts: true
      optional: false
  before_script:
    - echo "Configuring ssh"
    - INFO_FILE="${CI_PROJECT_DIR}/$[[ inputs.cloud-provider ]]/${CI_PIPELINE_ID}.json"
    - INSTANCE_IP=$(jq -r '.values.outputs.instance_ip.value' ${INFO_FILE})
    - chmod 400 "$SSH_PRIV_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$INSTANCE_IP" >> ~/.ssh/known_hosts
    - printf "%b" "Host instance\n\tHostName $INSTANCE_IP\n\tUser $SSH_USER\n\tPort 22\n\tIdentityFile $SSH_PRIV_KEY\n" > ~/.ssh/config
    - cat ~/.ssh/config
    - echo "Testing ssh connection"
    - ssh -o BatchMode=yes instance uptime

.outline-install: &outline-install
  stage: install
  script:
    - API_PORT=$(jq -r '.values.outputs.randomized_ports.value[0]' ${INFO_FILE})
    - KEYS_PORT=$(jq -r '.values.outputs.randomized_ports.value[0]' ${INFO_FILE})
    - echo "Sending script file to remote instance"
    - scp scripts/install-outline.sh instance:.
    - ssh -t instance "bash install-outline.sh"
    - scp instance:./outline-api.json .
    - mkdir ${CI_PROJECT_DIR}/outline && mv outline-api.json ${CI_PROJECT_DIR}/outline
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/outline
    expire_in: 30 days

aws-outline-install:
  <<: *outline-install
  rules:
    - if: '"$[[ inputs.cloud-provider ]]" == "aws" && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
      when: manual
  extends: .remote-access-template
  variables:
    SSH_USER: "${AWS_SSH_USER:-ubuntu}"
